// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260731064746_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.29");

            modelBuilder.Entity("Api.Models.Lugar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsServicioAlCiudadano")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitud")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitud")
                        .HasColumnType("REAL");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lugares");
                });

            modelBuilder.Entity("Api.Models.ReporteAccesibilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AjusteRazonable")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalisisIa")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("CertezaIa")
                        .HasColumnType("REAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("TEXT");

                    b.Property<int>("LugarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Severidad")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TipoBarreraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LugarId");

                    b.HasIndex("TipoBarreraId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("Api.Models.TipoBarrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("CriterioNorma")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TiposBarrera");
                });

            modelBuilder.Entity("Api.Models.ReporteAccesibilidad", b =>
                {
                    b.HasOne("Api.Models.Lugar", "Lugar")
                        .WithMany("Reportes")
                        .HasForeignKey("LugarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.TipoBarrera", "TipoBarrera")
                        .WithMany("Reportes")
                        .HasForeignKey("TipoBarreraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Lugar");

                    b.Navigation("TipoBarrera");
                });

            modelBuilder.Entity("Api.Models.Lugar", b =>
                {
                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("Api.Models.TipoBarrera", b =>
                {
                    b.Navigation("Reportes");
                });
#pragma warning restore 612, 618
        }
    }
}
